--PRIMARY KEYS
ALTER TABLE COLABORADOR          ADD CONSTRAINT pk_col_id   PRIMARY KEY ( col_id );
ALTER TABLE USUARIO              ADD CONSTRAINT pk_usu_id   PRIMARY KEY ( usu_id );
ALTER TABLE PRESIDENCIA          ADD CONSTRAINT pk_pre_id   PRIMARY KEY ( pre_id );
ALTER TABLE DIRETORIA            ADD CONSTRAINT pk_dir_id   PRIMARY KEY ( dir_id );
ALTER TABLE GERENCIA             ADD CONSTRAINT pk_ger_id   PRIMARY KEY ( ger_id );
ALTER TABLE NUCLEO               ADD CONSTRAINT pk_nuc_id   PRIMARY KEY ( nuc_id );
ALTER TABLE CONTRATOCOLABORADOR  ADD CONSTRAINT pk_coc_id   PRIMARY KEY ( coc_id );
ALTER TABLE NOTEBOOK             ADD CONSTRAINT pk_not_id   PRIMARY KEY ( not_id );
ALTER TABLE DESKTOP              ADD CONSTRAINT pk_des_id   PRIMARY KEY ( des_id );
ALTER TABLE MONITOR              ADD CONSTRAINT pk_mon_id   PRIMARY KEY ( mon_id );
ALTER TABLE PERIFERICO           ADD CONSTRAINT pk_pef_id   PRIMARY KEY ( pef_id );
ALTER TABLE KIT                  ADD CONSTRAINT pk_kit_id   PRIMARY KEY ( kit_id );
ALTER TABLE OCORRENCIA           ADD CONSTRAINT pk_oco_id   PRIMARY KEY ( oco_id );
ALTER TABLE IMPRESSORA           ADD CONSTRAINT pk_imp_id   PRIMARY KEY ( imp_id );
ALTER TABLE CONTRATOIMPRESSORA   ADD CONSTRAINT pk_coi_id   PRIMARY KEY ( coi_id );
ALTER TABLE NOTAFISCAL           ADD CONSTRAINT pk_nof_id   PRIMARY KEY ( nof_id );
ALTER TABLE LOCALIZACAO          ADD CONSTRAINT pk_loc_id   PRIMARY KEY ( loc_id );


--CHECKS
ALTER TABLE COLABORADOR           ADD CONSTRAINT CK_COL_NN_01   CHECK ( col_id IS NOT NULL );
ALTER TABLE COLABORADOR           ADD CONSTRAINT CK_COL_NN_02   CHECK ( col_datacadastro IS NOT NULL );
ALTER TABLE COLABORADOR           ADD CONSTRAINT CK_COL_NN_03   CHECK ( col_rf IS NOT NULL );
ALTER TABLE COLABORADOR           ADD CONSTRAINT CK_COL_NN_04   CHECK ( col_nome IS NOT NULL );

ALTER TABLE USUARIO               ADD CONSTRAINT CK_USU_NN_01   CHECK ( usu_id IS NOT NULL );
ALTER TABLE USUARIO               ADD CONSTRAINT CK_USU_NN_02   CHECK ( usu_datacadastro IS NOT NULL );
ALTER TABLE USUARIO               ADD CONSTRAINT CK_USU_NN_03   CHECK ( col_usu_idcolaborador IS NOT NULL );

ALTER TABLE PRESIDENCIA           ADD CONSTRAINT CK_PRE_NN_01   CHECK ( pre_id IS NOT NULL );
ALTER TABLE PRESIDENCIA           ADD CONSTRAINT CK_PRE_NN_02   CHECK ( pre_datacadastro IS NOT NULL );
ALTER TABLE PRESIDENCIA           ADD CONSTRAINT CK_PRE_NN_03   CHECK ( pre_descricao IS NOT NULL );
ALTER TABLE PRESIDENCIA           ADD CONSTRAINT CK_PRE_NN_04   CHECK ( pre_sigla IS NOT NULL );

ALTER TABLE DIRETORIA             ADD CONSTRAINT CK_DIR_NN_01   CHECK ( dir_id IS NOT NULL );
ALTER TABLE DIRETORIA             ADD CONSTRAINT CK_DIR_NN_02   CHECK ( dir_datacadastro IS NOT NULL );
ALTER TABLE DIRETORIA             ADD CONSTRAINT CK_DIR_NN_03   CHECK ( dir_descricao IS NOT NULL );
ALTER TABLE DIRETORIA             ADD CONSTRAINT CK_DIR_NN_04   CHECK ( dir_sigla IS NOT NULL );

ALTER TABLE GERENCIA              ADD CONSTRAINT CK_GER_NN_01   CHECK ( ger_id IS NOT NULL );
ALTER TABLE GERENCIA              ADD CONSTRAINT CK_GER_NN_02   CHECK ( ger_datacadastro IS NOT NULL );
ALTER TABLE GERENCIA              ADD CONSTRAINT CK_GER_NN_03   CHECK ( ger_descricao IS NOT NULL );
ALTER TABLE GERENCIA              ADD CONSTRAINT CK_GER_NN_04   CHECK ( ger_sigla IS NOT NULL );

ALTER TABLE NUCLEO                ADD CONSTRAINT CK_NUC_NN_01   CHECK ( nuc_id IS NOT NULL );
ALTER TABLE NUCLEO                ADD CONSTRAINT CK_NUC_NN_02   CHECK ( nuc_datacadastro IS NOT NULL );
ALTER TABLE NUCLEO                ADD CONSTRAINT CK_NUC_NN_03   CHECK ( nuc_descricao IS NOT NULL );

ALTER TABLE CONTRATOCOLABORADOR   ADD CONSTRAINT CK_COC_NN_01   CHECK ( coc_id IS NOT NULL );
ALTER TABLE CONTRATOCOLABORADOR   ADD CONSTRAINT CK_COC_NN_02   CHECK ( col_coc_idcolaborador IS NOT NULL );

ALTER TABLE NOTEBOOK              ADD CONSTRAINT CK_NOT_NN_01   CHECK ( not_id IS NOT NULL );
ALTER TABLE NOTEBOOK              ADD CONSTRAINT CK_NOT_NN_02   CHECK ( not_patrimonio IS NOT NULL );

ALTER TABLE DESKTOP               ADD CONSTRAINT CK_DES_NN_01   CHECK ( des_id IS NOT NULL );
ALTER TABLE DESKTOP               ADD CONSTRAINT CK_DES_NN_02   CHECK ( des_patrimonio IS NOT NULL );

ALTER TABLE MONITOR               ADD CONSTRAINT CK_MON_NN_01   CHECK ( mon_id IS NOT NULL );
ALTER TABLE MONITOR               ADD CONSTRAINT CK_MON_NN_02   CHECK ( mon_patrimonio IS NOT NULL );

ALTER TABLE PERIFERICO            ADD CONSTRAINT CK_PEF_NN_01   CHECK ( pef_id IS NOT NULL );

ALTER TABLE KIT                   ADD CONSTRAINT CK_KIT_NN_01   CHECK ( kit_id IS NOT NULL );
ALTER TABLE KIT                   ADD CONSTRAINT CK_KIT_NN_02   CHECK ( col_kit_idcolaborador IS NOT NULL );

ALTER TABLE OCORRENCIA            ADD CONSTRAINT CK_OCO_NN_01   CHECK ( oco_id IS NOT NULL );
ALTER TABLE OCORRENCIA            ADD CONSTRAINT CK_OCO_NN_02   CHECK ( col_oco_idcolaborador IS NOT NULL );

ALTER TABLE IMPRESSORA            ADD CONSTRAINT CK_IMP_NN_01   CHECK ( imp_id IS NOT NULL );
ALTER TABLE IMPRESSORA            ADD CONSTRAINT CK_IMP_NN_02   CHECK ( coi_imp_idcontrato IS NOT NULL );

ALTER TABLE CONTRATOIMPRESSORA    ADD CONSTRAINT CK_COI_NN_01   CHECK ( coi_id IS NOT NULL );
ALTER TABLE CONTRATOIMPRESSORA    ADD CONSTRAINT CK_COI_NN_02   CHECK ( coi_fornecedor IS NOT NULL );

ALTER TABLE NOTAFISCAL            ADD CONSTRAINT CK_NOF_NN_01   CHECK ( nof_id IS NOT NULL );
ALTER TABLE NOTAFISCAL            ADD CONSTRAINT CK_NOF_NN_02   CHECK ( nof_numero IS NOT NULL );

ALTER TABLE LOCALIZACAO           ADD CONSTRAINT CK_LOC_NN_01   CHECK ( loc_id IS NOT NULL );
ALTER TABLE LOCALIZACAO           ADD CONSTRAINT CK_LOC_NN_02   CHECK ( loc_homeoffice IS NOT NULL );